import Navbar from "@/components/nav.dropdown";
import "./globals.css";
import { Inter } from "next/font/google";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Maca Edu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="fixed top-0 z-10 p-4 bg-[#FFFFFF] w-full">
          <Navbar />
        </div>
        <div className={clsx("mx-auto bg-white flex flex-row")}>
          <main className="flex flex-grow w-full">{children}</main>
        </div>
      </body>
    </html>
  );
}
